### ISSUE TITLE
Problem reading scan configurations.

### ISSUE THREAD

**Issue by sklakegg** [kstechnologies/NIRScanNano_Android#1]
When only the two factory default scan configurations are stored on the device, the reading of scan configurations work. But when I added a custom configuration to my device, it get stuck at "Reading Scan Configurations... 0% 0/1". Maybe this is related to the added scan parameters in the new software version?

Setting the custom configuration as default configuration through the windows GUI and then just scanning with the phone seems to work though.

**Comment by KST-collin** [comment]
We have noticed an issue where the new scan configurations cause an issue with the current implementation of the Spectrum C Library. We are currently looking into the issue and being able to support the custom configurations.

**Comment by ganesh2shiv** [comment]
@collinmast: Any update on this?

**Comment by bobkressin** [comment]
@ganesh2shiv I realize this is a very old / open issue. We are currently revisiting this entire repo and considering a port to Kotlin and a modern tool chain. Thanks for your patience while we work through the process.

**Comment by sklakegg** [comment]
Hey, quite some time ago this, so I am closing this issue 🤖
